apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: edgecloud9-io-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - api.edgecloud9.io
      port:
        name: https-443-apiedgecloud9-io
        number: 443
        protocol: HTTPS
      tls:
        credentialName: apiedgecloud9-io
        mode: SIMPLE
        privateKey: sds
        serverCertificate: sds
