apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-edge-cloud
spec:
  gateways:
    - edge-cloud-micro-business-co-nz-gateway
  hosts:
    - edgecloud.micro-business.co.nz
  http:
    - match:
        - uri:
            prefix: "/"
          ignoreUriCase: true
      route:
        - destination:
            host: frontend.edge.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-edge-cloud
spec:
  gateways:
    - edge-cloud-micro-business-co-nz-gateway
  hosts:
    - apiedgecloud.micro-business.co.nz
  http:
    - match:
        - uri:
            prefix: "/"
          ignoreUriCase: true
      route:
        - destination:
            host: api-gateway.edge.svc.cluster.local
            port:
              number: 80
