--- 
  apiVersion: v1
  kind: Secret
  metadata: 
    labels: 
      app: kiali
    name: kiali
    namespace: istio-system
  type: Opaque
  data: 
    passphrase: cGFzc3dvcmQ=
    username: a2lhbGk=
