apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  # username: kiali
  username: a2lhbGk=
  # password: 123456
  passphrase: MTIzNDU2

