apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: api-edgecloud-zapto-org
spec:
  commonName: api-edgecloud.zapto.org
  dnsNames:
    - api-edgecloud.zapto.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: api-edgecloud-zapto-org-tls
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - api-edgecloud.zapto.org

