apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: edgecloud-zapto-org
spec:
  commonName: edgecloud.zapto.org
  dnsNames:
    - edgecloud.zapto.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: edgecloud-zapto-org-tls
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - edgecloud.zapto.org

