apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: idp-edgecloud-zapto-org
spec:
  commonName: idp-edgecloud.zapto.org
  dnsNames:
    - idp-edgecloud.zapto.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: idp-edgecloud-zapto-org-tls
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - idp-edgecloud.zapto.org

