--- 
  apiVersion: cert-manager.io/v1alpha2
  kind: Certificate
  metadata: 
    name: idp-edgecloud-zapto-org
  spec: 
    commonName: idp-edgecloud.zapto.org
    dnsNames: 
      - idp-edgecloud.zapto.org
    issuerRef: 
      kind: ClusterIssuer
      name: self-signed-ca-cluster-issuer
    secretName: idp-edgecloud-zapto-org
  
