apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: edgecloud-com
spec:
  commonName: edgecloud.com
  dnsNames:
    - edgecloud.com
    - api.edgecloud.com
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: edgecloud-com
