apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: edgecloud-com
spec:
  commonName: edgecloud.com
  dnsNames:
    - edgecloud.com
    - api.edgecloud.com
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
  secretName: edgecloud-com
