#!/usr/bin/env bash

DEFAULT_CONFIG="$(cd "$(dirname "$0")"; pwd -P)"/../config/default_kind_config.yaml
KIND_CONFIG="${KIND_CONFIG:-"$DEFAULT_CONFIG"}"

function print_help() {
	echo "Usage: ./$1 <start|stop>"
}

function start() {
	kind create cluster --config "$KIND_CONFIG" --wait 5m # Block until control plane is ready
	export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"

	# Deploy mongodb
	helm install mongo stable/mongodb
}

function stop() {
	helm delete mongo
	kind delete cluster
}

case $1 in
	start|stop) "$1" ;;
	*) print_help "$0" ;;
esac
