--- 
  apiVersion: cert-manager.io/v1alpha2
  kind: Certificate
  metadata: 
    name: idp-edge-cloud-com
  spec: 
    commonName: idp.edge-cloud.com
    dnsNames: 
      - idp.edge-cloud.com
    issuerRef: 
      kind: ClusterIssuer
      name: self-signed-ca-cluster-issuer
    secretName: idp-edge-cloud-com-tls
  
