apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: edgecloud-zapto-org
spec:
  secretName: edgecloud-zapto-org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  commonName: edgecloud.zapto.org
  dnsNames:
    - edgecloud.zapto.org
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: api-edgecloud-zapto-org
spec:
  secretName: api-edgecloud-zapto-org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  commonName: api-edgecloud.zapto.org
  dnsNames:
    - api-edgecloud.zapto.org
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: idp-edgecloud-zapto-org
spec:
  secretName: idp-edgecloud-zapto-org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  commonName: idp-edgecloud.zapto.org
  dnsNames:
    - idp-edgecloud.zapto.org
