apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: edgecloud-zapto-org
spec:
  secretName: edgecloud-zapto-org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  commonName: edgecloud.zapto.org
  dnsNames:
    - edgecloud.zapto.org
