apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: edge-cloud-gateway-https
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - hosts:
        - "*"
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: edgecloud-zapto-org
        mode: SIMPLE
        privateKey: sds
        serverCertificate: sds
