apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: edge-cloud-http
spec:
  hosts:
    - edgecloud.zapto.org
  gateways:
    - edge-cloud-gateway-http
  http:
    -
      match:
        -
          uri:
            prefix: /
      ignoreUriCase: true
      route:
        -
          destination:
            host: xxxxx
            port:
              number: 8089
