apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: edge-cloud-https
spec:
  hosts:
    - edgecloud.zapto.org
  gateways:
    - edge-cloud-gateway-https
  http:
    -
      match:
        -
          uri:
            prefix: /admin
      rewrite:
        uri: /
      ignoreUriCase: true
      route:
        -
          destination:
            host: frontend.edge.svc.cluster.local
            port:
              number: 80
    -
      match:
        -
          uri:
            prefix: /api
      rewrite:
        uri: /
      ignoreUriCase: true
      route:
        -
          destination:
            host: api-gateway.edge.svc.cluster.local
            port:
              number: 80
    -
      match:
        -
          uri:
            prefix: /idp
      rewrite:
        uri: /
      ignoreUriCase: true
      route:
        -
          destination:
            host: keycloak-http.edge.svc.cluster.local
            port:
              number: 80
